### PR TITLE
wrong attribute for image data

### PR DESCRIPTION
**Pull request by ilaurensnl**
Minor correction to docs.

### CODE REVIEW

**Comment by richard-scryber** [comment]
Hi - thanks for the check and patch. I think the code should follow the documentation (data-img is better in html source).
Is data-img not working for you?

**Comment by ilaurensnl** [comment]
test scenario's states 'img-data' as far I could find in the code; following the doc with 'data-img' did not seem to work with '5.0.4', it states no data source and will ignored the image (will not show alt="" also). 

I do agree that 'data-img' makes more sense; a colleague got stuck because it did not work; took a while before I noticed the data-img and img-data switch; haha.

**Comment by richard-scryber** [comment]
Perfect - this helps a lot. Thank you! 

Just done a quick check back in the version history, and you are absolutely right. The data-img is not in 5.0.4, but it is now in 5.0.5 (in beta). I suppose I am on a bit of a chicken and egg at the moment - update docs, release stable versions. 

I'm going to update the docs to make this clear. The img-data is still going to be valid, but preferred from 5.0.5 will be data-img.

And hope you like scryber too. If we can help with anything, just shout.

**Comment by ilaurensnl** [comment]
No problem, sorry for the late response. 

To be honest I did not suspect that might have happened because it wasn't on the stable version; so thanks for the head-up considering we can use the new syntaxes soon :) 

It's good that a lot of things are changing and becoming better; thanks for that :) 
Yeah we love it, At this point we did just basic things; and it works like a charm so far :)

**Comment by richard-scryber** [comment]
That is really awesome to hear, and yeah 5.0.5 is out and publicly available as of last weekend. Please go ahead and break it (I have found a couple of minor things already) :-)

If there's anything wanted, just shout.

**Pull request closed without merging**
