### PR TITLE
#107 SVG Paths with containing dots does not work in Culture de-DE

### PR DESCRIPTION
**Pull request by bykka**
There is an additional try to parse unit value with InvariantCulture

### CODE REVIEW

**Review by richard-scryber — APPROVED** [review]
Thanks, I will take it as I know it solves the immediate issue.

**Comment by richard-scryber** [comment]
> Do you have a plan to create a new version of the library that will include this pull request? My project is waiting for this fix.

Yeah - I can sort this today.
Can you do me a favour and just confirm on the locale settings too - so I can nail this for a future release. 👍

**Comment by bykka** [comment]
No problem, Could you just clarify a bit what kind of confirmation you need?

**Comment by richard-scryber** [comment]
Thanks Pavlo - I will sort the release first thing tomorrow, it is a bit late now for me, just to check and confirm. And thanks for the confirmation too 👍

**Pull request merged**
